// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlZf_x_6UOP7ClLPAv4eBKi30LNrBDnDY',
    appId: '1:235397335886:web:46570667626b7701352c1f',
    messagingSenderId: '235397335886',
    projectId: 'jalalert-e03b2',
    authDomain: 'jalalert-e03b2.firebaseapp.com',
    storageBucket: 'jalalert-e03b2.firebasestorage.app',
    measurementId: 'G-W4MG699Q19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS4ZwW5emLn3akkHMocgjW5Z043i8PSM4',
    appId: '1:235397335886:android:267b3f4e249284b3352c1f',
    messagingSenderId: '235397335886',
    projectId: 'jalalert-e03b2',
    storageBucket: 'jalalert-e03b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYX-NSVguLrL0MsyLRK7SeEfuY2NKchao',
    appId: '1:235397335886:ios:603133a8eadf3fbc352c1f',
    messagingSenderId: '235397335886',
    projectId: 'jalalert-e03b2',
    storageBucket: 'jalalert-e03b2.firebasestorage.app',
    iosBundleId: 'com.example.jalalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYX-NSVguLrL0MsyLRK7SeEfuY2NKchao',
    appId: '1:235397335886:ios:603133a8eadf3fbc352c1f',
    messagingSenderId: '235397335886',
    projectId: 'jalalert-e03b2',
    storageBucket: 'jalalert-e03b2.firebasestorage.app',
    iosBundleId: 'com.example.jalalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlZf_x_6UOP7ClLPAv4eBKi30LNrBDnDY',
    appId: '1:235397335886:web:c22941932dbbb4f8352c1f',
    messagingSenderId: '235397335886',
    projectId: 'jalalert-e03b2',
    authDomain: 'jalalert-e03b2.firebaseapp.com',
    storageBucket: 'jalalert-e03b2.firebasestorage.app',
    measurementId: 'G-VBBL3CVHDL',
  );
}
